apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-app
  labels:
    app: login-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service-app
  template:
    metadata:
      labels:
        app: login-service-app
    spec:
      containers:
      - name: login-service-app
        image: abhijitmishra2632/login-service:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: login-service-svc
spec:
  type: ClusterIP
  selector:
    app: login-service-app
  ports:
  - port: 80
    targetPort: 9001