apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-app
  labels:
    app: login-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service-app
  template:
    metadata:
      labels:
        app: login-service-app
    spec:
      containers:
      - name: login-service-app
        image: abhijitmishra2632/login-service:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 9001
        env: # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name

          - name: root_password # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-root-credentials
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: login-service-svc
  labels:
    name: login-service-svc
spec:
  type: ClusterIP
  selector:
    app: login-service-app
  ports:
  - port: 80
    targetPort: 9001